name: GHA for DevOps course

# Controls when the workflow will run
on:
  # push:
  #   branches: main
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job_1:
    runs-on: ubuntu-latest # type of runners a job can use
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo Hello, world!
          echo "File as artifact" >> artifact.txt

      - name: Upload an Artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: artifact_file
          path: artifact.txt
  
  job_2:
    runs-on: macos-12
    steps:
      - name: Show all default GH variables for a macOS runner
        run: env

  job_3:
    name: Persisting Data - download artifact from previous job
    needs: job_1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifact_file
  
      - name: utilise contents of artifact
        run: |
          cat artifact.txt | tee copy_artifact.txt
          echo "appended data" >> copy_artifact.txt
      
      - name: Upload annother artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: copy_artifact
          path: copy_artifact.txt

  job_3b:
    name: Show second artifact
    needs: job_3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: copy_artifact
      - name: display second artifact
        run: cat copy_artifact.txt
        
