name: GHA for DevOps course

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  exercise_1:
    runs-on: ubuntu-latest # type of runners a job can use
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo Hello, world!
          echo "File as artifact" >> artifact.txt

      - name: Upload an Artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: artifact_file
          path: artifact.txt
  
  
  exercise_2:
    runs-on: macos-12
    steps:
      - name: Show all default GH variables for a macOS runner
        run: env

  exercise_3:
    name: Persisting Data - download artifact from previous job
    needs: exercise_1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifact_file
          run: |
            cat artifact.txt | tee copy_artifact.txt
            echo "appended data" >> copy_artifact.txt
      
      - name: Another artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: artifact_copy
          path: artifact_copy.txt

  exercise_3b:
    needs: exercise_3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifact_copy
          run: cat copy_artifact.txt
        
