name: GHA for DevOps course

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  exercise_1:
    runs-on: ubuntu-latest # type of runner job uses
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
  
  exercise_2:
    name: Environment Vars
    runs-on: macos-12
    steps:
      - name: Show all default GH variables for a macOS runner
        run: env
