name: CI Go web-server

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go env
      uses: actions/setup-go@v4
      with:
        go-version: '>=1.17.0'

    - name: Build
      run: |
          echo "Building app..."
          cd go-app/
          go build -o go-app.exe
        #   can also use `go build -v ./...` to recursively look for and build all Go packages (root packages)

    - name: Run tests
      run: |
          echo "Running tests..."
          cd go-app/
          go test ./...
    
    - name: Upload app artifact
      uses: actions/upload-artifact@v4.4.0
      with:
        name: go-app.exe
        path: go-app/go-app.exe